# ==============================================================================
# Plantilla de Receta: Navegador Web Mozilla Firefox
# ==============================================================================

MODULE_ID="firefox"
MODULE_NAME="Mozilla Firefox - Perfiles de Usuario, Marcadores y Sesiones"
MODULE_TAGS=("web" "browser")

MODULE_PATHS=(
    ".mozilla/firefox"
)

IS_SENSITIVE=false
PURGE_AFTER_BACKUP=false
POST_RESTORE_HOOK=""
