# ==============================================================================
# Plantilla de Receta: Configuración Global de Git
# ==============================================================================

MODULE_ID="git-config"
MODULE_NAME="Git - Configuración de Usuario, Alias e Ignorados Globales"
MODULE_TAGS=("dev" "git")

MODULE_PATHS=(
    ".gitconfig"
    ".config/git/ignore"
)

IS_SENSITIVE=false
PURGE_AFTER_BACKUP=false
POST_RESTORE_HOOK=""
