# ==============================================================================
# Plantilla de Receta: JetBrains IntelliJ IDEA / IDEs JetBrains
# ==============================================================================

MODULE_ID="intellij"
MODULE_NAME="JetBrains IDEs - Configuraciones y Preferencias (.config/JetBrains)"
MODULE_TAGS=("dev" "ide")

MODULE_PATHS=(
    ".config/JetBrains"
)

IS_SENSITIVE=false
PURGE_AFTER_BACKUP=false
POST_RESTORE_HOOK=""
