# ==============================================================================
# Plantilla de Receta: Suite Ofimática LibreOffice
# ==============================================================================

MODULE_ID="libreoffice"
MODULE_NAME="LibreOffice - Preferencias de Usuario, Plantillas y Estilos"
MODULE_TAGS=("office")

MODULE_PATHS=(
    ".config/libreoffice"
)

IS_SENSITIVE=false
PURGE_AFTER_BACKUP=false
POST_RESTORE_HOOK=""
