# ==============================================================================
# Plantilla de Receta: Cliente de Correo Mozilla Thunderbird
# ==============================================================================

MODULE_ID="thunderbird"
MODULE_NAME="Mozilla Thunderbird - Perfiles de Correo, Cuentas y Libretas"
MODULE_TAGS=("office" "mail")

MODULE_PATHS=(
    ".thunderbird"
)

IS_SENSITIVE=false
PURGE_AFTER_BACKUP=false
POST_RESTORE_HOOK=""
