# ==============================================================================
# Plantilla de Receta: Visual Studio Code (Ajustes y Extensiones Estándar)
# ==============================================================================

MODULE_ID="vscode-standard"
MODULE_NAME="Visual Studio Code - Configuraciones y Atajos"
MODULE_TAGS=("dev" "editor")

MODULE_PATHS=(
    ".config/Code/User/settings.json"
    ".config/Code/User/keybindings.json"
    ".config/Code/User/snippets"
)

IS_SENSITIVE=false
PURGE_AFTER_BACKUP=false
POST_RESTORE_HOOK=""
